import type { Metadata } from 'next'
import './globalStyles/globals.scss'
import 'bootstrap/scss/bootstrap.scss'
import Layout from '@/components/layouts/layout'

export const metadata: Metadata = {
  title: 'Резервиум',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Layout children={children} />
      </body>
    </html>
  )
}
